In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv(r'D:\DS-ICG\kiwisaver_sample_wk9.csv')

# Task 1: Data Inspection

In [3]:
data.head()

,Name,Firm Name,Branding Name,Holdings,Global Category,Morningstar Rating,Domicile,Fund Legal Structure,Equity Style,Inception Date,Manager Name,Manager Tenure,Net Assets Date,Net Assets Size,Net Assets Share Class
0,AMP IL no E Fee NZ Share (RN),AMP Group,AMP,59,New Zealand Equity,3.0,New Zealand,Open Ended Investment Company,Mid Growth,3/02/1993,NaN,NaN,NaN,135202.500,81121.500
1,AMP KiwiSaver AMP Income Generator,AMP Group,AMP,689,Moderate Allocation,NaN,New Zealand,Open Ended Investment Company,Mid Blend,28/07/2016,NaN,NaN,28/02/2017,861.923,517.154
2,AMP KiwiSaver ANZ Balanced Plus,AMP Group,AMP,1544,Aggressive Allocation,3.0,New Zealand,Open Ended Investment Company,Large Growth,1/10/2007,NaN,NaN,28/02/2017,146665.955,87999.573
3,AMP Prem PSS OnePath NZ Shares,AMP Group,AMP,125,Australia & New Zealand Equity,3.0,New Zealand,Open Ended Investment Company,Mid Growth,9/08/2004,NaN,NaN,28/02/2017,3176.420,1905.852
4,ANZ Default KiwiSaver Scheme Cnsrv(Dflt),ANZ New Zealand Investments Limited,ANZ,1024,Cautious Allocation,4.0,New Zealand,Open Ended Investment Company,Mid Growth,1/10/2007,Stuart Millar,9.42,15/03/2017,705818.111,423490.867

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 15 columns):
Name                      76 non-null object
Firm Name                 76 non-null object
Branding Name             76 non-null object
Holdings                  76 non-null int64
Global Category           76 non-null object
Morningstar Rating        40 non-null float64
Domicile                  76 non-null object
Fund Legal Structure      76 non-null object
Equity Style              76 non-null object
Inception Date            76 non-null object
Manager Name              33 non-null object
Manager Tenure            33 non-null float64
Net Assets Date           75 non-null object
Net Assets Size           76 non-null float64
Net Assets Share Class    76 non-null float64
dtypes: float64(4), int64(1), object(10)
memory usage: 9.0+ KB

# Problematic Columns: 
Following columns require some pre-processing (A fair amount of records have Null values for these columns):

Morningstar Rating        40 non-null float64
Manager Name              33 non-null object
Manager Tenure            33 non-null float64
Net Assets Date           75 non-null object

# Task 2: Imputation of the missing data (Columns mentioned above)

In [ ]:
print(data['Morningstar Rating'].mean())
print(data['Morningstar Rating'].mode())
print(data['Morningstar Rating'].median())

In [9]:
data['Morningstar Rating'].describe()

count    40.000000
mean      3.725000
std       0.905468
min       1.000000
25%       3.000000
50%       4.000000
75%       4.000000
max       5.000000
Name: Morningstar Rating, dtype: float64

In [10]:
data[data['Morningstar Rating'].isnull()]

,Name,Firm Name,Branding Name,Holdings,Global Category,Morningstar Rating,Domicile,Fund Legal Structure,Equity Style,Inception Date,Manager Name,Manager Tenure,Net Assets Date,Net Assets Size,Net Assets Share Class
1,AMP KiwiSaver AMP Income Generator,AMP Group,AMP,689,Moderate Allocation,NaN,New Zealand,Open Ended Investment Company,Mid Blend,28/07/2016,NaN,NaN,28/02/2017,861.923,517.154
22,BNZ KiwiSaver First Home Buyer Fund,BNZ Investment Services Limited,Bank of New Zealand,2456,Cautious Allocation,NaN,New Zealand,Open Ended Investment Company,Large Blend,17/09/2015,NaN,NaN,14/03/2017,27564.969,16538.981
27,Booster KiwiSaver Capital Guaranteed,Booster Financial Services Limited,Grosvenor,151,Miscellaneous,NaN,New Zealand,Open Ended Investment Company,Large Blend,1/07/2014,David Beattie,2.67,28/02/2017,32777.503,19666.502
28,Booster KiwiSaver Default Saver,Booster Financial Services Limited,Grosvenor,159,Cautious Allocation,NaN,New Zealand,Open Ended Investment Company,Large Blend,1/07/2014,David Beattie;Nic Craven;,2.67,28/02/2017,23651.194,14190.716
32,Booster KiwiSaver Socially Rsp Inv Bal,Booster Financial Services Limited,Grosvenor,147,Allocation,NaN,New Zealand,Open Ended Investment Company,Large Blend,1/07/2014,David Beattie,2.67,28/02/2017,18747.062,11248.237
35,FC KiwiSaver Scheme's Active Balanced,ASB Group Investments Limited,ASB,1237,Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,1/10/2007,NaN,NaN,31/12/2014,7094.312,4256.587
36,FC KiwiSaver Scheme's Active Cnsrv,ASB Group Investments Limited,ASB,1212,Moderate Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,1/10/2007,NaN,NaN,31/12/2014,1794.037,1076.422
37,FC KiwiSaver Scheme's Active Growth,ASB Group Investments Limited,ASB,1218,Aggressive Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,1/10/2007,NaN,NaN,31/12/2014,8047.739,4828.643
38,Fidelity KiwiSaver-Aggressive Kiwi Fund,Booster Financial Services Limited,Grosvenor,76,Aggressive Allocation,NaN,New Zealand,Open Ended Investment Company,Large Blend,1/10/2007,NaN,NaN,31/10/2014,15280.369,9168.221
39,Fidelity KiwiSaver-Balanced Kiwi Fund,Booster Financial Services Limited,Grosvenor,75,Allocation,NaN,New Zealand,Open Ended Investment Company,Large Blend,1/10/2007,NaN,NaN,31/10/2014,94957.184,56974.310
40,Fidelity KiwiSaver-Ethical Kiwi,Booster Financial Services Limited,Grosvenor,113,Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,14/05/2008,NaN,NaN,31/10/2014,10302.667,6181.600
41,Fidelity KiwiSaver-Growth Kiwi Fund,Booster Financial Services Limited,Grosvenor,75,Aggressive Allocation,NaN,New Zealand,Open Ended Investment Company,Large Blend,1/10/2007,NaN,NaN,31/10/2014,42618.096,25570.858
44,Forsyth Barr KiwiSaver Balanced Port,Forsyth Barr Limited,Forsyth Barr,153,Aggressive Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,26/06/2008,NaN,NaN,29/09/2016,12116.528,7269.917
45,Forsyth Barr KiwiSaver Growth Portfolio,Forsyth Barr Limited,Forsyth Barr,153,Aggressive Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,26/06/2008,NaN,NaN,29/09/2016,10738.997,6443.398
51,Mercer KiwiSaver Growth,Mercer (N.Z.) Limited,Mercer,1602,Aggressive Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,18/02/2015,Phillip Houghton-Brown,2.08,28/02/2017,29364.475,17618.685
53,Mercer KiwiSaver Moderate,Mercer (N.Z.) Limited,Mercer,1364,Moderate Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,18/02/2015,Phillip Houghton-Brown,2.08,28/02/2017,38324.385,22994.631
54,Mercer Super Trust KiwiSaver Active Bal,Mercer (N.Z.) Limited,Mercer,1228,Aggressive Allocation,NaN,New Zealand,Open Ended Investment Company,Large Blend,1/10/2007,NaN,NaN,31/05/2015,87240.978,52344.587
55,Mercer Super Trust KiwiSaver Conserv,Mercer (N.Z.) Limited,Mercer,1039,Moderate Allocation,NaN,New Zealand,Open Ended Investment Company,Large Blend,1/10/2007,NaN,NaN,31/05/2015,633.303,379.982
56,Mercer Super Trust KiwiSaver Growth,Mercer (N.Z.) Limited,Mercer,1239,Aggressive Allocation,NaN,New Zealand,Open Ended Investment Company,Large Blend,1/10/2007,NaN,NaN,31/05/2015,6859.595,4115.757
57,Mercer Super Trust KiwiSaver High Growth,Mercer (N.Z.) Limited,Mercer,1131,Aggressive Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,1/10/2007,NaN,NaN,31/05/2015,9139.787,5483.872
58,Mercer Super Trust KiwiSaver Moderate,Mercer (N.Z.) Limited,Mercer,1213,Allocation,NaN,New Zealand,Open Ended Investment Company,Large Blend,1/10/2007,NaN,NaN,31/05/2015,2240.726,1344.436
59,Mercer Super Trust KiwiSaver Shares,Mercer (N.Z.) Limited,Mercer,862,Australia & New Zealand Equity,NaN,New Zealand,Open Ended Investment Company,Large Growth,1/10/2007,NaN,NaN,31/05/2015,5335.246,3201.148
60,Mercer Super Trust KiwiSaver TransTasman,Mercer (N.Z.) Limited,Mercer,74,Australia & New Zealand Equity,NaN,New Zealand,Open Ended Investment Company,Mid Growth,1/10/2007,NaN,NaN,31/01/2015,1881.585,1128.951
62,Milford KiwiSaver Conservative Fund,Milford Funds Limited,Milford Funds,361,Cautious Allocation,NaN,New Zealand,Open Ended Investment Company,Mid Growth,1/10/2012,David Lewis,1.50,15/03/2017,23663.555,14198.133
63,NZ Defence Force KiwiSaver Balanced,Mercer (N.Z.) Limited,Mercer,1538,Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,9/10/2015,NaN,NaN,28/02/2017,17475.715,10485.429
64,NZ Defence Force KiwiSaver Conservative,Mercer (N.Z.) Limited,Mercer,1306,Cautious Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,9/10/2015,NaN,NaN,28/02/2017,916.695,550.017
65,NZ Defence Force KiwiSaver Growth,Mercer (N.Z.) Limited,Mercer,1602,Aggressive Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,9/10/2015,NaN,NaN,28/02/2017,4589.997,2753.998
66,NZ Defence Force KiwiSaver Moderate,Mercer (N.Z.) Limited,Mercer,1364,Moderate Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,9/10/2015,NaN,NaN,28/02/2017,1084.035,650.421
67,NZ Funds KiwiSaver Growth Strategy,New Zealand Funds Management Limited,New Zealand Funds,185,Miscellaneous,NaN,New Zealand,Open Ended Investment Company,Mid Value,21/09/2010,NaN,NaN,28/02/2017,60645.442,36387.265
68,NZ Funds KiwiSaver Inflation Strategy,New Zealand Funds Management Limited,New Zealand Funds,182,Miscellaneous,NaN,New Zealand,Open Ended Investment Company,Mid Value,21/09/2010,NaN,NaN,28/02/2017,43965.166,26379.100
70,SIL NZ Share,ANZ New Zealand Investments Limited,ANZ,145,New Zealand Equity,NaN,New Zealand,Open Ended Investment Company,Mid Growth,1/03/1992,Mark Brown;Craig Brown;,11.25,31/10/2016,15396.723,9238.034
71,Simplicity KiwiSaver Balanced Fund,Simplicity (NZ) Limited,Simplicity NZ,66,Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,1/09/2016,NaN,NaN,14/03/2017,15381.980,9229.188
72,Simplicity KiwiSaver Conservative Fund,Simplicity (NZ) Limited,Simplicity NZ,31,Cautious Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,1/09/2016,NaN,NaN,14/03/2017,3951.668,2371.001
73,Simplicity KiwiSaver Growth Fund,Simplicity (NZ) Limited,Simplicity NZ,66,Aggressive Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,1/09/2016,NaN,NaN,14/03/2017,47602.397,28561.438
74,Staples Rodway KiwiSaver Balanced,Staples Rodway Superannuation Limited,Staples Rodway,1361,Aggressive Allocation,NaN,New Zealand,Open Ended Investment Company,Large Growth,1/10/2007,NaN,NaN,29/02/2016,15219.139,9131.483
75,Staples Rodway KiwiSaver Growth,Staples Rodway Superannuation Limited,Staples Rodway,873,Aggressive Allocation,NaN,New Zealand,Open Ended Investment Company,Large Blend,1/10/2007,NaN,NaN,29/02/2016,7621.845,4573.107

In [11]:
med_mr = data['Morningstar Rating'].median() # I am taking median because 4.0 is the median and 50% values are below 4.0 in the available data
def remove_na_mr(row):
    if pd.isnull(row['Morningstar Rating']):
        return med_mr
    else:
        return row['Morningstar Rating']

In [15]:
print("Mean of original 'Morningstar Rating':",data['Morningstar Rating'].mean()," - Mean after imputation",data.apply(remove_na_mr, axis=1).mean())
print("Median of original 'Morningstar Rating':",data['Morningstar Rating'].median()," - Median after imputation",data.apply(remove_na_mr, axis=1).median())

Mean of original 'Morningstar Rating': 3.725  - Mean after imputation 3.8552631578947367
Median of original 'Morningstar Rating': 4.0  - Median after imputation 4.0

In [16]:
data['MR_new'] = data.apply(remove_na_mr, axis=1)

In [22]:
print("Mean of original 'Morningstar Rating':",data['Morningstar Rating'].mean()," - Mean after imputation",data['MR_new'].mean())
print("Median of original 'Morningstar Rating':",data['Morningstar Rating'].median()," - Median after imputation",data['MR_new'].median())

Mean of original 'Morningstar Rating': 3.725  - Mean after imputation 3.8552631578947367
Median of original 'Morningstar Rating': 4.0  - Median after imputation 4.0

# Task 3: Unique, 2 most used & 2 least used "Equity Style" values

In [37]:
data['Equity Style'].describe()

count               76
unique               5
top       Large Growth
freq                33
Name: Equity Style, dtype: object

In [40]:
print('Unique "Equity Styles":',data['Equity Style'].unique())

Unique "Equity Styles": ['Mid Growth' 'Mid Blend' 'Large Growth' 'Large Blend' 'Mid Value']

In [45]:
es_cols = data['Equity Style'].value_counts().index.tolist() 
es_values = data['Equity Style'].value_counts().values.tolist()

In [47]:
print('Most used:',es_cols[0],'(',es_values[0],')',' - 2nd Most used:',es_cols[1],'(',es_values[1],')')
print('Least used:',es_cols[-1],'(',es_values[-1],')',' - 2nd Least used:',es_cols[-2],'(',es_values[-2],')')

Most used: Large Growth ( 33 )  - 2nd Most used: Large Blend ( 28 )
Least used: Mid Value ( 2 )  - 2nd Least used: Mid Blend ( 3 )

# Task 4: Mapping of "Morningstar Rating" from [5,4,3,2,1] to ['Awsome','Good','Average','bad','Awful']

In [48]:
data['MR_str'] = data['MR_new'].map(lambda s: 'Awful' if s==1 else 'Bad' if s==2 else 'Average' if s==3 else 'Good' if s==4 else 'Awesome')

In [51]:
data[['MR_str','MR_new']].head(10)

    MR_str  MR_new
0  Average     3.0
1     Good     4.0
2  Average     3.0
3  Average     3.0
4     Good     4.0
5  Average     3.0
6  Average     3.0
7     Good     4.0
8  Awesome     5.0
9     Good     4.0

# Task 5: Data Aggregation using GroupBy

In [52]:
data.columns

Index(['Name', 'Firm Name', 'Branding Name', 'Holdings', 'Global Category',
       'Morningstar Rating', 'Domicile', 'Fund Legal Structure',
       'Equity Style', 'Inception Date', 'Manager Name', 'Manager Tenure',
       'Net Assets Date', 'Net Assets Size', 'Net Assets Share Class',
       'MR_new', 'MR_str'],
      dtype='object')

In [63]:
data.groupby(['Branding Name','Equity Style'])['Holdings','Net Assets Size'].mean()

                                     Holdings  Net Assets Size
Branding Name       Equity Style
AMP                 Large Growth  1544.000000     1.466660e+05
                    Mid Blend      689.000000     8.619230e+02
                    Mid Growth      92.000000     6.918946e+04
ANZ                 Large Growth  1543.111111     5.191668e+05
                    Mid Growth     438.666667     2.460913e+05
ASB                 Large Blend   1319.500000     1.191800e+06
                    Large Growth  1222.333333     5.645363e+03
Aon                 Large Blend    265.000000     1.911613e+04
                    Mid Growth     384.000000     8.220035e+04
Bank of New Zealand Large Blend   2456.800000     1.425594e+05
Fisher Funds        Large Growth   209.500000     6.073430e+05
Forsyth Barr        Large Growth   153.000000     1.142776e+04
Generate            Mid Blend       56.000000     1.074962e+05
                    Mid Growth     108.000000     5.560979e+04
Grosvenor           Large Blend    132.307692     6.634276e+04
                    Large Growth   113.000000     1.030267e+04
Mercer              Large Blend   1179.750000     2.424365e+04
                    Large Growth  1358.272727     1.039314e+05
                    Mid Growth      74.000000     1.881585e+03
Milford Funds       Mid Growth     429.000000     5.880018e+04
New Zealand Funds   Mid Value      183.500000     5.230530e+04
Simplicity NZ       Large Growth    54.333333     2.231202e+04
Staples Rodway      Large Blend    873.000000     7.621845e+03
                    Large Growth  1361.000000     1.521914e+04

# Task 6: Data Aggregation using pivot tables.

In [60]:
pd.pivot_table(data, index=['Branding Name','Equity Style'], values=['Holdings','Net Assets Size'], aggfunc="mean")

                                     Holdings  Net Assets Size
Branding Name       Equity Style
AMP                 Large Growth  1544.000000     1.466660e+05
                    Mid Blend      689.000000     8.619230e+02
                    Mid Growth      92.000000     6.918946e+04
ANZ                 Large Growth  1543.111111     5.191668e+05
                    Mid Growth     438.666667     2.460913e+05
ASB                 Large Blend   1319.500000     1.191800e+06
                    Large Growth  1222.333333     5.645363e+03
Aon                 Large Blend    265.000000     1.911613e+04
                    Mid Growth     384.000000     8.220035e+04
Bank of New Zealand Large Blend   2456.800000     1.425594e+05
Fisher Funds        Large Growth   209.500000     6.073430e+05
Forsyth Barr        Large Growth   153.000000     1.142776e+04
Generate            Mid Blend       56.000000     1.074962e+05
                    Mid Growth     108.000000     5.560979e+04
Grosvenor           Large Blend    132.307692     6.634276e+04
                    Large Growth   113.000000     1.030267e+04
Mercer              Large Blend   1179.750000     2.424365e+04
                    Large Growth  1358.272727     1.039314e+05
                    Mid Growth      74.000000     1.881585e+03
Milford Funds       Mid Growth     429.000000     5.880018e+04
New Zealand Funds   Mid Value      183.500000     5.230530e+04
Simplicity NZ       Large Growth    54.333333     2.231202e+04
Staples Rodway      Large Blend    873.000000     7.621845e+03
                    Large Growth  1361.000000     1.521914e+04

# Task 7:

In [57]:
#data[data['Age'].isnull()].groupby('Sex')['Sex'].count()
data.groupby('Manager Name')['Morningstar Rating'].mean()

Manager Name
David Beattie                2.333333
David Beattie;Nic Craven;    2.750000
David Lewis                       NaN
John Smith                   3.750000
Jonathan Windust             5.000000
Mark Brighouse               4.000000
Mark Brown                   4.000000
Mark Brown;Craig Brown;           NaN
Phillip Houghton-Brown       4.000000
Stuart Millar                4.000000
Name: Morningstar Rating, dtype: float64

In [61]:
pd.pivot_table(data, index=['Manager Name'], values=['Morningstar Rating'], aggfunc='mean')

                           Morningstar Rating
Manager Name
David Beattie                        2.333333
David Beattie;Nic Craven;            2.750000
John Smith                           3.750000
Jonathan Windust                     5.000000
Mark Brighouse                       4.000000
Mark Brown                           4.000000
Phillip Houghton-Brown               4.000000
Stuart Millar                        4.000000

In [65]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 17 columns):
Name                      76 non-null object
Firm Name                 76 non-null object
Branding Name             76 non-null object
Holdings                  76 non-null int64
Global Category           76 non-null object
Morningstar Rating        40 non-null float64
Domicile                  76 non-null object
Fund Legal Structure      76 non-null object
Equity Style              76 non-null object
Inception Date            76 non-null object
Manager Name              33 non-null object
Manager Tenure            33 non-null float64
Net Assets Date           75 non-null object
Net Assets Size           76 non-null float64
Net Assets Share Class    76 non-null float64
MR_new                    76 non-null float64
MR_str                    76 non-null object
dtypes: float64(5), int64(1), object(11)
memory usage: 10.2+ KB

In [68]:
data[data['Manager Name'].isnull()].groupby('Morningstar Rating')['Morningstar Rating'].count()

Morningstar Rating
3.0    5
4.0    5
5.0    4
Name: Morningstar Rating, dtype: int64

In [69]:
data[data['Manager Name'].isnull()].groupby('MR_new')['MR_new'].count()

MR_new
3.0     5
4.0    34
5.0     4
Name: MR_new, dtype: int64

In [70]:
data[data['Manager Name'].isnull()].groupby('MR_str')['MR_str'].count()

MR_str
Average     5
Awesome     4
Good       34
Name: MR_str, dtype: int64